### ISSUE TITLE
fail to compile sketch rtc_format on a Arduino UNO with a DS3231 

### ISSUE THREAD

**Issue by wj4pi** [NeiroNx/RTCLib#1]
Hi looking for the best DS3231 library got here error:
...\RTCLib_by_NeiroN\RTClib.cpp: In member function 'uint8_t DS1302::begin()':
...\RTCLib_by_NeiroN\RTClib.cpp:309:15: error: 'write0' was not declared in this scope
  write0(0, sec);

Working with sketch rtc_format with a DS3231 on a Arduino UNO
Your library not yet suitable for DS3231? 
No worries take another one.

**Comment by NeiroNx** [comment]
try delete lines 306,307,308,309 in RTClib.cpp
`	write(7,0);
	uint8_t sec = read(0);
	sec |= (1 << 7);
	write0(0, sec);
`
I am do not know why it appear in this version. It deleted in my local copy.
