### ISSUE TITLE
Library is not updated in Arduino library manager

### ISSUE THREAD

**Issue by AlexIII** [NeiroNx/RTCLib#22]
Hi!
You seem to forget to update the version number in `library.properties`, so Arduino library manager won't fetch the new release.

**Comment by NeiroNx** [comment]
i am create new tag v1.5.8 with same versions in file
https://github.com/NeiroNx/RTCLib/blob/v1.5.8/library.properties#L2
https://github.com/NeiroNx/RTCLib/blob/v1.5.8/library.json#L9

**Comment by AlexIII** [comment]
Strange. The library manager usually fetches new versions fast, if the release complies to the guidelines.

**Comment by JiaJiaJiang** [comment]
still 1.5.4 in  Arduino library manager now🤔
