### ISSUE TITLE
Calling begin could drift clock by 1 second/minute/hour/etc

### ISSUE THREAD

**Issue by MinusWall** [NeiroNx/RTCLib#28]
In DS1302::begin:
https://github.com/NeiroNx/RTCLib/blob/f915e23cb030188a1ed222030ef84e821c0bcf19/src/RTClib.cpp#L425

I think below lines should be removed - I don't see their purpose there and sometimes it is substracting 1 second from clock (try few resets to see accumulation). 
From my understanding it is reading seconds from clock, and then saving them (read 59, clock changes to 00 seconds + 1 minute, save 59 to clock and it goes +1 minute again, the same with hour, day, etc).

    uint8_t sec = read(0);
    sec &= 0x7F;
    write(0, sec);

**Comment by AlexIII** [comment]
I think the idea is to start the RTC if it's not running currently. The datasheet says:
> Bit 7 of the seconds register is defined as the clock halt (CH) flag. When this bit is set to logic 1, the clock oscillator is stopped and the DS1302 is placed into a low-power standby mode with a current drain of less than 100nA. When this bit is written to logic 0, the clock will start. The initial power-on state is not defined

So, we really need to change the lines
https://github.com/NeiroNx/RTCLib/blob/f915e23cb030188a1ed222030ef84e821c0bcf19/src/RTClib.cpp#L426-L427 to
```
if(sec & 0x80) {
    sec &= 0x7F;
    write(0, sec);
}
```

**Comment by MinusWall** [comment]
Agreed, if clock is halted, it can't change its fields anyway.

**Comment by 45gfg9** [comment]
Yeah, this is the problem about DS1302 that I've fixed before... (#20)
And just as I going over datasheet (again, aww) @AlexIII gave a great solution, thanks
Would you like to open a pull request or I'll just push directly?

**Comment by MinusWall** [comment]
Just push, thank you :)
