### ISSUE TITLE
Not Compiling with Seeeduino XIAO

### ISSUE THREAD

**Issue by Achimoto** [NeiroNx/RTCLib#33]
Compiler finishes with "exit status 1, Error compiling for board Seeeduino XIAO."

- You sent me a fix in march, which works fine. But it seems not to be included in the current download of your lib.
- Besides, the arduino library manager still loads 1.5.4.

Could you be so kind to update both ?
I am writing an project article for the MAKE Magazine where I want to use your excellent lib.

**Comment by AlexIII** [comment]
#22 
The Arduino server ignores updates of this library for some reason. We should probably submit an issue in [Arduino repo](https://github.com/arduino/Arduino)

**Comment by 45gfg9** [comment]
Arduino IDE version updated (long ago).
