### ISSUE TITLE
DS1302 not working

### ISSUE THREAD

**Issue by ch4vi** [NeiroNx/RTCLib#5]
I'm using your rtc_format example with myDS1302 RTC Module with all the pins connected properly but the  clock is stuck in 00.00.2000  00:00:00. 
I made it work with another basic library but I was trying to use DateTime structs.

**Comment by NeiroNx** [comment]
it do not tested with 1302 yet. Only tests with 1307. Can you correct the
library and make push on github?

2017-06-26 0:30 GMT+04:00 Chavi Anyó <notifications@github.com>:

**Comment by SpaceAceMonkey** [comment]
I had this same issue. I don't think your library code is the problem. If you pull the RST/CE pin high, you will get the proper time back from the DS1302. The time _is_ being saved, but you will always get 00.00.2000 back from the RTC when the RST pin is low.

Make sure your RST pin is connected and set to high, and you should be good to go.

**Comment by boragurgen** [comment]
Would be awesome if this worked on DS1302. I use it and don't know how i will get the time from computer without entering manually.
