### ISSUE TITLE
ESP8266 porting

### ISSUE THREAD

**Issue by zoomx** [NeiroNx/RTCLib#6]
I got some errors compiling for ESP8266 because the library uses Wire1 in non AVR platforms. ESP8266 uses Wire.

So I changed some lines at the beginning of RTClib.cpp in this way
`#ifdef __AVR__
 #include <avr/pgmspace.h>
 #define WIRE Wire
#elif defined(ESP8266)			//***
 #include <pgmspace.h>
 #define WIRE Wire              //****
#else
 #define PROGMEM
 #define pgm_read_byte(addr) (*(const unsigned char *)(addr))
 #define WIRE Wire1
#endif
`

It compiles but I am not sure that I wrote correctly the IF chain.

**Comment by NeiroNx** [comment]
Please make Pull request, then i am can accept that.

**Comment by dimpen** [comment]
As @zoomx mentioned you have to add in RTClib.cpp the following lines to compile for ESP8266
```
#elif defined(ESP8266) 
#include <pgmspace.h> 
#define WIRE Wire
```
Also added `Wire.begin(2, 14); // SDA, SCL` before `rtc.begin();` for the correct pins.
Tested with Sparkfun's "The Thing" ESP8266 (Normal and Dev Board)

**Comment by stefschin** [comment]
I had same problem, I had to add this code manually, Why isn't added to RTClib.cpp??
